sudo: required
dist: trusty
language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: false
before_install:
  - sudo apt-get install -y --force-yes python-pip python2.7-dev libxext-dev python-qt4 pyqt4-dev-tools build-essential
  - ln -s /usr/lib/python2.7/dist-packages/PyQt4/ ~/virtualenv/lib/python2.7/site-packages/
  - ln -s /usr/lib/python2.7/dist-packages/sip.so ~/virtualenv/lib/python2.7/site-packages/
  - sudo add-apt-repository http://www.openfoam.org/download/ubuntu
  - sudo apt-get -qq update
  - sudo apt-get install -y --force-yes openfoam240
  - sudo apt-get install -y --force-yes paraviewopenfoam410
  - sudo apt-get install -y --force-yes libfreetype6-dev libpng12-dev
  - pip install -r requirements.txt
  - ./install_external.sh
  - . /opt/openfoam240/etc/bashrc
  - source /opt/openfoam240/etc/bashrc
install:
  - python setup.py install
script:
  - petroSym
#after_success:
#  - petroSym
